# Generated by Django 6.0.1 on 2026-01-24 14:41

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_contactmessage_failedpayment_donate_to_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedpayment',
            name='address_line_one',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='amount',
            field=django_cryptography.fields.encrypt(models.DecimalField(decimal_places=2, max_digits=10)),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=254)),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=30)),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=30)),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=20)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address_line_one',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address_line_two',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=django_cryptography.fields.encrypt(models.DecimalField(decimal_places=2, max_digits=10)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=100)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=254)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=30)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=30)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='message',
            field=django_cryptography.fields.encrypt(models.TextField(blank=True)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=20)),
        ),
    ]
