# Generated by Django 6.0.1 on 2026-02-09 10:52

import django_cryptography.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_alter_failedpayment_address_line_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='failedpayment',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='amount',
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='address_line_one',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500)),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address_line_one',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=500)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address_line_two',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=500)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='city',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=django_cryptography.fields.encrypt(models.EmailField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='first_name',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_name',
            field=django_cryptography.fields.encrypt(models.CharField(blank=True, max_length=255)),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255)),
        ),
    ]
