# Generated by Django 6.0.1 on 2026-02-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_remove_failedpayment_amount_remove_payment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='failedpayment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
