# Generated by Django 6.0.1 on 2026-02-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_failedpayment_amount_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='failedpayment',
            name='address_line_one',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='failedpayment',
            name='phone',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address_line_one',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='address_line_two',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='payment',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='last_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='phone',
            field=models.CharField(max_length=255),
        ),
    ]
